# Generated by Django 5.2.5 on 2025-09-17 08:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_type', models.CharField(max_length=50)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('context_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('order_confirmation', 'Order Confirmation'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('receipt', 'Payment Receipt'), ('asset_liquidation', 'Asset Liquidation Request'), ('sell_item_submitted', 'Sell Item Submitted'), ('sell_item_approved', 'Sell Item Approved'), ('sell_item_rejected', 'Sell Item Rejected'), ('new_order_admin', 'New Order (Admin)'), ('new_user_admin', 'New User Registration (Admin)'), ('sell_item_review_admin', 'Sell Item Review Required (Admin)'), ('low_stock_admin', 'Low Stock Alert (Admin)'), ('payment_failed_admin', 'Payment Failed (Admin)')], max_length=50, unique=True)),
                ('recipient_type', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], max_length=10)),
                ('subject', models.CharField(help_text='Use {variable} for dynamic content', max_length=200)),
                ('template_path', models.CharField(help_text='Path to HTML template', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['email_type'],
            },
        ),
    ]
