# Generated by Django 5.2.5 on 2025-09-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
