# Generated by Django 5.2.5 on 2025-09-09 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customerservicepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerServicePage',
        ),
    ]
