# Generated by Django 5.2.5 on 2025-09-05 20:14

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='SuccessDirectMarketStore', max_length=200)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('site_favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('paystack_public_key', models.CharField(blank=True, max_length=200)),
                ('paystack_secret_key', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="WhatsApp number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.CharField(max_length=255)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('footer_about_text', models.TextField(blank=True, help_text='Short description for footer', max_length=500)),
                ('copyright_text', models.CharField(default='© 2024 SuccessDirectMarketStore. All rights reserved.', max_length=200)),
                ('business_hours', models.TextField(blank=True, help_text="Enter business hours, e.g., 'Mon-Fri: 9AM-6PM'")),
                ('flash_sales_enabled', models.BooleanField(default=True)),
                ('blog_enabled', models.BooleanField(default=True)),
                ('user_reviews_enabled', models.BooleanField(default=True)),
                ('welcome_email_subject', models.CharField(default='Welcome to SuccessDirectMarketStore!', max_length=200)),
                ('order_confirmation_subject', models.CharField(default='Order Confirmation - #{order_number}', max_length=200)),
                ('receipt_email_subject', models.CharField(default='Payment Receipt - #{order_number}', max_length=200)),
                ('default_shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0.075, help_text='Tax rate as decimal (e.g., 0.0750 for 7.5%)', max_digits=5)),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
