# Generated by Django 5.2.5 on 2025-09-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='countdown_duration_hours',
            field=models.PositiveIntegerField(default=24, help_text='Countdown duration in hours'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='countdown_enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable countdown timer'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='countdown_reset_daily',
            field=models.BooleanField(default=True, help_text='Reset countdown daily at midnight'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_banner_button_action',
            field=models.CharField(default='flash sale', help_text='Search term when button is clicked', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_banner_button_text',
            field=models.CharField(default='Shop Flash Sale', help_text='Hero banner button text', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_banner_enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable hero banner on homepage'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_banner_image',
            field=models.ImageField(blank=True, help_text='Hero banner background image', null=True, upload_to='hero_banner/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_banner_subtitle',
            field=models.CharField(default='Up to 70% off on selected items!', help_text='Hero banner subtitle', max_length=300),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_banner_title',
            field=models.CharField(default='Flash Sale', help_text='Hero banner title', max_length=200),
        ),
    ]
