# Generated by Django 5.2.5 on 2025-09-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfiguration_countdown_duration_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10, help_text='Send low stock alert when product stock falls to or below this number'),
        ),
    ]
