# Generated by Django 5.2.5 on 2025-09-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfiguration_low_stock_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='order_confirmation_subject',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='receipt_email_subject',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='welcome_email_subject',
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_banner_button_text',
            field=models.CharField(blank=True, default='Shop Flash Sale', help_text='Hero banner button text', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_banner_subtitle',
            field=models.CharField(blank=True, default='Up to 70% off on selected items!', help_text='Hero banner subtitle', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_banner_title',
            field=models.CharField(blank=True, default='Flash Sale', help_text='Hero banner title', max_length=200, null=True),
        ),
    ]
