# Generated by Django 5.2.5 on 2025-09-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_siteconfiguration_order_confirmation_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_button_enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable hero banner button on homepage'),
        ),
    ]
