# Generated by Django 5.2.5 on 2025-09-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siteconfiguration_hero_button_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_banner_enabled',
            field=models.BooleanField(default=False, help_text='Enable/disable hero banner on homepage'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='hero_button_enabled',
            field=models.BooleanField(default=False, help_text='Enable/disable hero banner button on homepage'),
        ),
    ]
