# Generated by Django 5.2.5 on 2025-09-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image for the blog post', upload_to='blog/'),
        ),
    ]
